### ISSUE TITLE
Add support for Docker building service on Windows

### ISSUE THREAD

**Issue by ANicholasson** [AutoPacker-OSS/autopacker#11]

**Comment by libanbn** [comment]
Docker building are blocked on Windows because the instructions to build are biased towards UNIX.

https://github.com/AutoPacker-OSS/AutoPacker/blob/develop/file-delivery-api/src/main/java/no/autopacker/filedeliveryapi/service/DockerService.java

**Comment by ANicholasson** [comment]
@libanbn Could you provide more information on what you have tried, experienced and maybe how you would have "attacked" this issue?

**Comment by libanbn** [comment]
Basically, there is a set of basic commands on Linux that cannot run on standard Windows machines when building the Docker images. One must add the Windows-equivalent set of commands to build images when a Windows machine is detected
