### ISSUE TITLE
Change the Regex for validateName in NewOrganization

### ISSUE THREAD

**Issue by MrPrecise** [AutoPacker-OSS/AutoPacker#117]
Description
-

Change the Regex [here](https://github.com/AutoPacker-OSS/autopacker/blob/05027e66e6dd3bd02996a80b1c79fdcf5ffcc059/web-application/src/views/ProfileDashboard/NewOrganization/NewOrganization.js#L124) in the NewOrganization.js
Right now you can't and add a organization with spaces in their names, many organization have spaces so this should be made support for.

**Screenshots:**

![image](https://user-images.githubusercontent.com/16646169/110210343-7f896300-7e91-11eb-9d8f-a26596706bb8.png)

**Comment by ANicholasson** [comment]
This wouldn't work if we are going to create project images from/for organizations, so should keep this check. Same as it is on GitHub for example. Or you could add an extra field to the organization entity named "displayName" which is the text that is displayed. But the "name" should still meet those requirements.
