### ISSUE TITLE
Users without admin access can not see the organization page

### ISSUE THREAD

**Issue by MrPrecise** [AutoPacker-OSS/AutoPacker#121]
Description
-

When you try to open up an organization without being the admin of the organization you will be given an error based on the role you're given. We must implment a way where you can view organization as lower than ADMIN access users.

### Steps to Reproduce

1. Become member of a organization 
2. Your role needs to be lower than ADMIN
3. When you try to enter that organization the page

**Expected behavior:**

You can look at your organization with the role you have assgined, but more limited of what an admin would see.

**Actual behavior:**

Page throws an internal error 500

**Reproduces how often:**

Every user you have that's not a ADMIN

**Screenshots:**
![image](https://user-images.githubusercontent.com/16646169/110838097-5c502080-82a2-11eb-8766-9f0dadbd17e4.png)

**Comment by ANicholasson** [comment]
@MrPrecise Fixed?

**Comment by ANicholasson** [comment]
@MrPrecise Still an issue?

**Comment by MrPrecise** [comment]
@ANicholasson Yeah, this is working now after the role changes that was introduced. I will close this.
