### ISSUE TITLE
Issue with incompatible chromedriver - webtests

### ISSUE THREAD

**Issue by ANicholasson** [AutoPacker-OSS/autopacker#13]
keyword: Selenium

**Comment by ANicholasson** [comment]
Would be nice to have some sort of script that detects OS and browser version and installs (in a safe not intrusive way) the corresponding drivers that is needed to run the browser tests.

**Comment by strazdinsg** [comment]
It could be a bit hard to do it correctly for all 3 OSes. I will update the Readme with instructions on how to download the necessary chromedriver and where to store it.
It also seems that the docker-solution for the webapp does not work either. The chromium driver version is not correct, and it can't access the web app, unsless it is in the same network where the webapp container.

**Comment by strazdinsg** [comment]
I wrote a Readme that explains how to set up the ChromeDriver
