### ISSUE TITLE
Seperate personal and organization projects in file api

### ISSUE THREAD

**Issue by MrPrecise** [AutoPacker-OSS/AutoPacker#137]
Description
-

Right now there are no modules in the GENERAL API portion of the the site, this means when you request a project without any modules like you can see in the picture under. Only the meta data about the project iis saved when it's submitted, however the modules are not. 

Add a way so the modules gets added with the submission of the project to an organization.

UPDATE
-
The team decided to handle everything in File API instead. We still need to make a way to seperate the two different kind of proejcts, if they are organization based or personal. 

**Screenshots:**
![image](https://user-images.githubusercontent.com/16646169/112041220-6a295f80-8b46-11eb-9339-2ec81a32825a.png)

**Comment by ANicholasson** [comment]
@libanbn We should use file delivery api for this, but are there any seperators we can use to seperate private projects from organization projects?

**Comment by libanbn** [comment]
No mechanisms have been implemented to distinguish private projects from projects in organizations at the moment

**Comment by ANicholasson** [comment]
@MrPrecise

**Comment by MrPrecise** [comment]
I talked to Aron about this, that we should utilize File API to handle the project and I will update the description of this issue while working on it.

**Comment by ANicholasson** [comment]
@MrPrecise Pretty sure this is closed as it might be solved after @strazdinsg refactored this process.

**Comment by strazdinsg** [comment]
@MrPrecise Yes, one can check the organization_id for the project (organization property). If that is not null, the project belongs to an organization.
One bug though: when a project submission is accepted by the organization, the owner of the organization should be set as the owner for the project. I.e., the original owner "misses" the ownership. Otherwise the organization owner will not have any ability to manage the project.

**Comment by ANicholasson** [comment]
> @MrPrecise Yes, one can check the organization_id for the project (organization property). If that is not null, the project belongs to an organization.
> One bug though: when a project submission is accepted by the organization, the owner of the organization should be set as the owner for the project. I.e., the original owner "misses" the ownership. Otherwise the organization owner will not have any ability to manage the project.

@MrPrecise Should create another issue for this
