### ISSUE TITLE
Update "Last updated" for a project to a nicer format

### ISSUE THREAD

**Issue by strazdinsg** [AutoPacker-OSS/AutoPacker#152]
Project overview page
![image](https://user-images.githubusercontent.com/8917445/113304939-cd638080-9302-11eb-98c5-5cca74c11fc1.png)

**Comment by ANicholasson** [comment]
Somehow this got broken. We use date-fns for date & time formatting. Should give that a look

**Comment by MrPrecise** [comment]
@ANicholasson Pretty sure you used only date and not timestamp right? 
Formated it like this:
![image](https://user-images.githubusercontent.com/16646169/113415957-92c01d80-93c0-11eb-86c3-82bdf01ba605.png)
