### ISSUE TITLE
Error message when Module upload failed

### ISSUE THREAD

**Issue by strazdinsg** [AutoPacker-OSS/AutoPacker#155]
Currently there is no error message if uploading module file fails. 
The backend returns error code (such as 401), but the frontend still shows "Successfully added module", even though the upload failed.

Steps to reproduce:
* Open a project used by a regular 
* Add module, select Java 11, upload a JAR file
* If the endpoint returns an error code, there should be an error in the frontend

**Comment by ANicholasson** [comment]
@strazdinsg I'm pretty sure the little fix in #188 should solve this problem. Could you try and verify this?

**Comment by ANicholasson** [comment]
I'll merge the request to make it easier for testing, but leave the issue open until verified
