### ISSUE TITLE
"undefined Projects" when organization has no projects

### ISSUE THREAD

**Issue by strazdinsg** [AutoPacker-OSS/AutoPacker#158]
When an organization has no projects, its dashboard shows a wrong message:
![image](https://user-images.githubusercontent.com/8917445/113402045-b2494d00-93a4-11eb-9a18-eaddf9fff7d3.png)

Should say "No projects", or something like that. No "undefined"

**Comment by MrPrecise** [comment]
It should say the {organization name} Projects, like this:
![image](https://user-images.githubusercontent.com/16646169/113414491-62c34b00-93bd-11eb-9eb3-c57e33d9f0fb.png)

I made a new organization locally but I couldn't recreate it showing "undefined".
