### ISSUE TITLE
API demand a bootstrap.yml file after merging

### ISSUE THREAD

**Issue by MrPrecise** [AutoPacker-OSS/AutoPacker#159]
Description
-

After mering of the APIs, when you try to start up the API the program demands a bootstrap.yml in api\target\classes to start up.
The dependencies for this got removed when the APIs got merged but the program still won't open without having an empty file in the folder. Find out why?

**Full error message**
[bootstraperrror.txt](https://github.com/AutoPacker-OSS/autopacker/files/6248848/bootstraperrror.txt)

**Screenshot**
![image](https://user-images.githubusercontent.com/16646169/113404034-d65a5d80-93a7-11eb-8539-414f8b8c81c7.png)

**Comment by libanbn** [comment]
Fixed in #168 and file removed in fb19515
