### ISSUE TITLE
Accept option on project request is broken

### ISSUE THREAD

**Issue by MrPrecise** [AutoPacker-OSS/AutoPacker#185]
Description
-

Declining an project request is going fine but when you try to accept a project it will only give you an error.

[![Image from Gyazo](https://i.gyazo.com/77117be46f74f76b03f42aec415d910f.gif)](https://gyazo.com/77117be46f74f76b03f42aec415d910f)

**Comment by ANicholasson** [comment]
Duplicate of #181
