### ISSUE TITLE
docker-compose run on server: FTB Infinity Evolved server crashes. Try on own server 

### ISSUE THREAD

**Issue by ANicholasson** [AutoPacker-OSS/AutoPacker#24]

**Comment by libanbn** [comment]
By default, the FTB Infinity Evolve requires quite some RAM. It's recommended to have at least a few gigabytes of RAM available on the server.

If there are other problems causing the crash, please provide the logs from the server using `docker logs {container-name}`

It may be useful to have a description of recommended server specs before the deployment screen on the website.
