### ISSUE TITLE
Remove the check that validates if the folder exists when deploying to server

### ISSUE THREAD

**Issue by ANicholasson** [AutoPacker-OSS/AutoPacker#31]
This isnt necessary as we already have the docker image on docker hub. So can remove this "validation".

**Comment by libanbn** [comment]
Can you link where this happens? And is it on file delivery API or the server manager? @ANicholasson

**Comment by ANicholasson** [comment]
I believe the validation happens in file delivery, but not sure if there is an "issue" with it. Can't remember the background for the issue so closing it for now.
