### ISSUE TITLE
Handle JSON Exception for incoming data

### ISSUE THREAD

**Issue by ANicholasson** [AutoPacker-OSS/AutoPacker#4]
For example, https://github.com/AutoPacker-OSS/AutoPacker/blob/a4f7d6fcf07d0c5afd2215a54023db2b4974295c/user-service/src/main/java/no/autopacker/userservice/controller/RESTController.java#L66

It will crash if someone sends an empty JSON {}.

Need to go through all the code and clean this issue.

**Comment by chander97** [comment]
@ANicholasson I would like to take this up.
Before we create new user, a simple validate of input payload is needed, which checks for mandatory fields.

**Comment by ANicholasson** [comment]
@chander97 Sure👍

**Comment by chander97** [comment]
@ANicholasson before I raise PR, just want to know, shall we have simple validation of whether both username etc are present in body
(or)
shall I do schema validation. Ex of schema:
{
"username": "string",
"password": "string"
}

**Comment by ANicholasson** [comment]
@chander97 sure. Tbh, this project is the result of a bachelor project. So there are a lot of flaws here and there. So we are open for changes, ideas and such as well. I can create a dummy user so you can test the application and make yourself familiar if you want.
