### ISSUE TITLE
Add IP validation to the input field

### ISSUE THREAD

**Issue by ANicholasson** [AutoPacker-OSS/AutoPacker#54]
![image](https://user-images.githubusercontent.com/17160743/106495128-949e5b00-64bb-11eb-8287-25946e89e97d.png)

For example use RegEx to check for "." between characters and that there are min: 1 and max 3. chars for each ".".

Should be at least 3 ".". example: 123.45.678.9

**Comment by MrPrecise** [comment]
This issue was fixed with this pull request
https://github.com/AutoPacker-OSS/AutoPacker/pull/55
