### ISSUE TITLE
Factorio gets internal server error when you try to set up a server

### ISSUE THREAD

**Issue by MrPrecise** [AutoPacker-OSS/AutoPacker#93]
Description
-

When we trying to setup Factorio server with with AutoPacker we will be getting a Status 500, "Internal Server Error", somewhere in the process of setting up the Factorio server. It fails, screen shot and full error message bellow.

### Steps to Reproduce

1. Add factorio to your project
2. Make a new server
3. Add the project to the server
4. Run the docker compose to set it up on your server

**Expected behavior:**

A stable build of Factorio Server 1.1 set up with standard settings

**Actual behavior:**

Status 500, "Internal Server Error"
[Faulty Docker Compose.zip](https://github.com/AutoPacker-OSS/autopacker/files/6030778/Faulty.Docker.Compose.zip)

**Reproduces how often:**

Everytime I've tried to set it up on a server

**Screenshots:**

<details>
<summary>Docker Compose</summary>

![image](https://user-images.githubusercontent.com/16646169/108883321-957f6400-7605-11eb-9597-6d9f5ed5f0f8.png)

</details>

**Comment by ANicholasson** [comment]
I believe this might be related to the file not existing on file delivery anymore due to reset. Try and create a new project with a new factorio server module and deploy again

**Comment by ANicholasson** [comment]
@MrPrecise
