### ISSUE TITLE
Find the issue why project deployment is not working locally

### ISSUE THREAD

**Issue by ANicholasson** [AutoPacker-OSS/AutoPacker#95]
### Title

Service returns 500: Internal Server Error when trying to deploy a project to a controlled server

### Description

This issue only happens when running the system locally.

### Steps to Reproduce

1. Add project to server
2. Click the deploy button on the project

**Expected behavior:**

The project should be deployed

**Actual behavior:**

500: Internal Server Error

**Comment by libanbn** [comment]
Hello,

What operating system was it running on when the exception occurred? And is the project ran inside a Docker environment or is it manually run using IDE/Maven/Java? Also, if you have the stack trace, it would give a good overview on where to start.

**Comment by ANicholasson** [comment]
Ah, that might be the reason indeed. Might be an issue with the service using Linux bindings, thus it won't work on Windows?

I Will try and reproduce it on my Linux workstation later

**Comment by libanbn** [comment]
Possibly related to issue #11
